metadata:
  name: code-hellven-api
data:
  application.properties: |-
    logstash.servers=logstash-code-hellven:80

    spring.data.mongodb.host=mongodb-code-hellven
    spring.data.mongodb.database=code-hellven

    server.port=8081

    spring.profiles.active=prod

    spring.main.allow-bean-definition-overriding=true

    management.endpoints.web.exposure.include=*
    management.endpoints.web.base-path=/manage

    spring.boot.admin.client.url=http://spring-management/admin
    spring.boot.admin.client.instance.name=Code-Hellven
    spring.boot.admin.client.instance.prefer-ip=true

    keycloak.enabled=true
    keycloak.auth-server-url=http://keycloak-code-hellven-code-hellven.192.168.99.104.nip.io/auth
    keycloak.realm=code-hellven
    keycloak.resource=code-hellven
    keycloak.public-client=false
    keycloak.credentials.secret=b93b704c-6a3b-4e6b-b262-33a34fa97dc1
    keycloak.cors=true
    keycloak.bearer-only=true
    keycloak.ssl-required = external
    keycloak.realm-key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJBrJ8Jpw6bie7C1FS94/cIIqOEwEFOqaq4VX1QxPPTTRjJsxplZ/8TPA7o8nSFzfLQZg0nEIz1ryDlWd9DT3MECAwEAAQ==

    keycloak.security-constraints[0].authRoles[0]=*
    keycloak.security-constraints[0].securityCollections[0].patterns[0]=/api/*

    keycloak.security-constraints[1].authRoles[0]=actuator
    keycloak.security-constraints[1].securityCollections[0].patterns[0]=/manage/*

    keycloak.security-constraints[2].securityCollections[0].patterns[0]=/manage/health
    keycloak.security-constraints[2].securityCollections[0].patterns[1]=/manage/info

    keycloak.security-constraints[3].securityCollections[0].patterns[0]=/manage/loggers/*
    keycloak.security-constraints[3].securityCollections[0].omitted-methods[0]=POST