metadata:
  name: code-hellven-api
spec:
  template:
    spec:
      containers:
        - env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.properties
            - name: SPRING_PROFILES_ACTIVE
              value: mongodb, prod
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-code-hellven
                  key: database-user
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-code-hellven
                  key: database-password
          livenessProbe:
            httpGet:
              path: /manage/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /manage/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 20
          volumeMounts:
            - name: code-hellven-api
              mountPath: /config
      volumes:
        - name: code-hellven-api
          configMap:
            name: code-hellven-api